### PR TITLE
Add a flag to append a fixed HTTP header to all responses.

### PR DESCRIPTION
**Pull request by gomlgs**
Note: The latest centurylink/golang-builder image does not build this project because of Golang 1.7 dependencies; I used a local build.

I also had to fix the echo.Run* calls which have changed to echo.Start*.

### CODE REVIEW

**Comment by PierreZ** [comment]
Hi, thanks for your interest for GoStatic. I wasn't aware that people other than me was using goStatic, and then I saw DockerHub stats. I'm currently rewriting a new version. Why do you need to add headers?

**Comment by gomlgs** [comment]
Thanks a lot for developing this!
Regarding headers, I wanted to add some default caching headers to all responses.

**Comment by PierreZ** [comment]
Due to complete rewrite on my side, can you upgrade your PR? I looked over your code, it should be easy to adapt it to the new version. Don't hesitate to ping me if you're having trouble.

**Comment by gomlgs** [comment]
Done.

**Comment by PierreZ** [comment]
Merged. Thanks for the PR!

**Pull request merged**
